scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: usv/base_link
        min_x: -2.75
        max_x: 2.75
        min_y: -1.8
        max_y: 1.8
        min_z: -1.0
        max_z: 1.0
        invert: True