---
# Example coast configuration from:
# https://github.com/osrf/mbzirc/wiki/Running-the-coast-environment
model_name: 'usv'
model_type: 'usv'
position:
  xyz: [10, 40, 0.3]
  rpy: [0, 0, 0]
payload:
  slot6:
    sensor: 'mbzirc_planar_lidar'
    rpy: [0, 0, 0]
